#include <stdio.h>
#include <stdlib.h>

/* change to 1 for debug info to be printed: */
#define DO_SHOW 1
#include "arch/cisc.h"
#include "macros.h"
int main()
{
  START_MACHINE;

#include "arch/char.lib"
#include "arch/io.lib"
#include "arch/math.lib"
#include "arch/string.lib"
#include "arch/system.lib"
#include "arch/scheme.lib"
<<<<<<< HEAD
=======

//make_pair
 MAKE_PAIR:
  PUSH(FP);
  MOV(FP, SP);
  PUSH(IMM(3));
  CALL(MALLOC);
  DROP(IMM(1));
  MOV(IND(R0), T_PAIR);
  MOV(INDD(R0, 1), SCMARG(0));
  MOV(INDD(R0, 2), SCMARG(1));
  POP(FP);
  RETURN;

CAR:
  
  PUSH(FP);
  MOV(FP, SP);
  CMP(SCMNARGS,IMM(1));
  JUMP_NE(L_NOT_VALID_ARGUMENTS);
  MOV(R1,SCMARG(0));
  CMP(IND(R1), IMM(T_PAIR));
  JUMP_NE(L_NOT_PAIR);
  MOV(R0,INDD(R1,IMM(1)));
  POP(FP);
  RETURN;

CDR:
  PUSH(FP);
  MOV(FP, SP);
  CMP(SCMNARGS,IMM(1));
  JUMP_NE(L_NOT_VALID_ARGUMENTS);
  MOV(R1,SCMARG(0));
  CMP(IND(R1), IMM(T_PAIR));
  JUMP_NE(L_NOT_PAIR);
  MOV(R0,INDD(R1,IMM(2)));
  POP(FP);
  RETURN;

 IS_BOOL:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_BOOL));
  JUMP_EQ(L_IS_SOB_BOOL_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_BOOL_EXIT);
 L_IS_SOB_BOOL_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_BOOL_EXIT:
  POP(FP);
  RETURN;

IS_NUNBER:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_NUMBER));
  JUMP_EQ(L_IS_SOB_NUMBER_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_NUMBER_EXIT);
 L_IS_SOB_NUMBER_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_NUMBER_EXIT:
  POP(FP);
  RETURN;

IS_STRING:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_STRING));
  JUMP_EQ(L_IS_SOB_STRING_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_STRING_EXIT);
 L_IS_SOB_STRING_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_STRING_EXIT:
  POP(FP);
  RETURN;

  IS_CHAR:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_CHAR));
  JUMP_EQ(L_IS_SOB_CHAR_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_CHAR_EXIT);
 L_IS_SOB_CHAR_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_CHAR_EXIT:
  POP(FP);
  RETURN;


IS_SYMBOL:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_SYMBOL));
  JUMP_EQ(L_IS_SOB_SYMBOL_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_SYMBOL_EXIT);
 L_IS_SOB_SYMBOL_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_SYMBOL_EXIT:
  POP(FP);
  RETURN;

IS_VECTOR:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_VECTOR));
  JUMP_EQ(L_IS_SOB_VECTOR_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_VECTOR_EXIT);
 L_IS_SOB_VECTOR_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_VECTOR_EXIT:
  POP(FP);
  RETURN;

IS_PAIR:
  PUSH(FP);
  MOV(FP, SP);
  MOV(R0, SCMARG(0));
  CMP(IND(R0), IMM(T_PAIR));
  JUMP_EQ(L_IS_PAIR_VECTOR_TRUE);
  MOV(R0, IMM(0));
  JUMP(L_IS_SOB_PAIR_EXIT);
 L_IS_SOB_PAIR_TRUE:
  MOV(R0, IMM(1));
 L_IS_SOB_PAIR_EXIT:
  POP(FP);
  RETURN;

  JUMP(CONTINUE);


>>>>>>> bdfe7a797523ec3411f0f4282c7798901a5a2d85

 CONTINUE:
