(((((lambda (a . rest)
      (lambda (b . rest)
        (((lambda (a . rest) (lambda (b . rest) ((a b) (lambda (x . rest) (lambda (y . rest) y)))))
    ((lambda (n . rest)
       ((n (lambda (x . rest) (lambda (x . rest) (lambda (y . rest) y))))
        (lambda (x . rest) (lambda (y . rest) x))))
     (((lambda (a . rest)
         (lambda (b . rest)
     ((b (lambda (n . rest)
           ((lambda (p . rest) (p (lambda (a . rest) (lambda (b . rest) b))))
      ((n (lambda (p . rest)
            (((lambda (a . rest)
          (lambda (b . rest) (lambda (c . rest) ((c a) b))))
        ((lambda (n . rest)
           (lambda (s . rest)
             (lambda (z) (s ((n s) z)))))
         ((lambda (p . rest)
            (p (lambda (a . rest) (lambda (b . rest) a))))
          p)))  
             ((lambda (p . rest)
          (p (lambda (a . rest) (lambda (b . rest) a))))
        p))))
       (((lambda (a . rest)
           (lambda (b . rest) (lambda (c . rest) ((c a) b))))
         (lambda (x . rest) (lambda (y . rest) y)))
        (lambda (x . rest) (lambda (y . rest) y)))))))
      a)))
       a)
      b)))
   ((lambda (n . rest)
      ((n (lambda (x . rest) (lambda (x . rest) (lambda (y . rest) y))))
       (lambda (x . rest) (lambda (y . rest) x))))
    (((lambda (a . rest)
        (lambda (b . rest)
    ((b (lambda (n . rest)
          ((lambda (p . rest) (p (lambda (a . rest) (lambda (b . rest) b))))
           ((n (lambda (p . rest)
           (((lambda (a . rest)
         (lambda (b . rest) (lambda (c . rest) ((c a) b))))
             ((lambda (n . rest)
          (lambda (s . rest)
            (lambda (z) (s ((n s) z)))))
        ((lambda (p . rest)
           (p (lambda (a . rest) (lambda (b . rest) a))))
         p)))
            ((lambda (p . rest)
         (p (lambda (a . rest) (lambda (b . rest) a))))
             p))))
      (((lambda (a . rest)
          (lambda (b . rest) (lambda (c . rest) ((c a) b))))
        (lambda (x . rest) (lambda (y . rest) y)))
       (lambda (x . rest) (lambda (y . rest) y)))))))
     a)))
      b)
     a)))))
    ((lambda (n . rest)
       ((lambda (p . rest) (p (lambda (a . rest) (lambda (b . rest) b))))
  ((n (lambda (p . rest)
        (((lambda (a . rest) (lambda (b . rest) (lambda (c . rest) ((c a) b))))
    ((lambda (n . rest) (lambda (s . rest) (lambda (z) (s ((n s) z)))))
     ((lambda (p . rest) (p (lambda (a . rest) (lambda (b . rest) a)))) p)))
         (((lambda (a . rest)
       (lambda (b . rest)
         ((b (a (lambda (a . rest)
            (lambda (b . rest)
        ((a (lambda (n . rest)
              (lambda (s . rest)
          (lambda (z) (s ((n s) z))))))
         b)))))
          (lambda (x . rest) (lambda (y . rest) y)))))
     ((lambda (p . rest) (p (lambda (a . rest) (lambda (b . rest) a)))) p))
    ((lambda (p . rest) (p (lambda (a . rest) (lambda (b . rest) b)))) p)))))
   (((lambda (a . rest) (lambda (b . rest) (lambda (c . rest) ((c a) b))))
     (lambda (x . rest) x))
    (lambda (x . rest) x)))))
     (lambda (x . rest) (lambda (y . rest) (x (x (x (x (x y)))))))))
   (((lambda (a . rest)
       (lambda (b . rest)
   ((b (a (lambda (a . rest)
      (lambda (b . rest)
        ((a (lambda (n . rest)
        (lambda (s . rest) (lambda (z) (s ((n s) z))))))
         b)))))
    (lambda (x . rest) (lambda (y . rest) y)))))
     (((lambda (a . rest)
   (lambda (b . rest)
     ((b (a (lambda (a . rest)
        (lambda (b . rest)
          ((a (lambda (n . rest)
          (lambda (s . rest) (lambda (z) (s ((n s) z))))))
           b)))))
      (lambda (x . rest) (lambda (y . rest) y)))))
       ((lambda (x . rest) (lambda (y . rest) (x (x (x y)))))
  (lambda (x . rest) (lambda (y . rest) (x (x y))))))
      (lambda (x . rest) (lambda (y . rest) (x (x (x y)))))))
    (lambda (x . rest) (lambda (y . rest) (x (x (x (x (x y)))))))))
  #t)
 #f)