(or)
(or 1)
(or #f)
(or 100)
(or ((lambda (x) x) #f))
(or ((lambda (x) x) #f) 1)
(or ((lambda (x) x) #t))
(or ((lambda (x) x) #t) 1)
(or #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f 1)
(or #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #t)
(or #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f ((lambda () (+ 1 2))))
(or 1 #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t)
((lambda (a b c)
	(or a b c 1)) #f #f #f 1)
((lambda (f g)
	(or (f #f) (g #t))) (lambda (x) x) (lambda (x) (if x 100 200)) )
((lambda (x)
	(or ((lambda (x) #f) 1) ((lambda (x y) (or #f x y)) #f 123) )) 1)
