(or)
(or 1)
(or #f)
(or 100)
(or ((lambda (x) x) #f))
(or ((lambda (x) x) #f) 1)
(or ((lambda (x) x) #t))
(or ((lambda (x) x) #t) 1)
(or #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f 1)
(or #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #t)
(or #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f #f ((lambda () (+ 1 2))))
(or 1 #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t #t)
